month_s = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug',
           'Sept', 'Oct', 'Nov', 'Dec']

# List of endings for each number 1 to 31
end = ['st', 'nd', 'rd'] + 17 * ['th'] \
      + ['st', 'nd', 'rd'] + 7 * ['th'] \
      + ['st']


def e_dates():
    days: set[str] = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}
    return days


year = input('Year: ')
month: str = input('Month: '.title())
day = input('Day: ')

month_num = int(month)
day_num = int(day)

# Subtract 1 from month and day for correct index

month_name = month_s[month_num - 1]
ordinal = day + end[day_num - 1]

print(month_name + ' ' + ordinal + ', ' + year)
